# -*- coding: utf-8 -*-
"""instagram_reach_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d-TZd2Hh1Szo82t5x_rKeiuwtsDUvkvP

let’s start the task of analyzing the reach of my Instagram account by importing the necessary Python libraries and the dataset.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveRegressor

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

data = pd.read_csv("/content/Instagram data.csv", encoding = 'latin1')
print(data.head())

data.isnull().sum()

data.info()

"""let's start with analyzing the reach of Instagram posts. First, look at the distribution of impressions that I have received from home."""

plt.figure(figsize=(10, 8))
plt.style.use('fivethirtyeight')
plt.title("Distribution of Impressions from Home")
sns.distplot(data['From Home'])
plt.show()

"""The impressions I get from the home section on Instagram shows how much my posts reach my followers. Looking at the impressions from home, it's hard to reach all my followers daily. Now, let's look at the distribution of the impressions that I received from hashtags."""

plt.figure(figsize=(10, 8))
plt.title("Distribution of Impressions from Hashtags")
sns.distplot(data['From Hashtags'])
plt.show()

"""Hashtags are tools we use to categorize our posts on Instagram so that we can reach more people based on the kind of content we are creating. Looking at hashtags impressions shows that not all posts can be reached using hashtags, but many new users can be reached from hashtags. Now, let's look at the distribution of impressions that I have received from the explore section of Instagram."""

plt.figure(figsize=(10, 8))
plt.title("Distribution of Impressions from Explore")
sns.distplot(data['From Explore'])
plt.show()

"""let's have a look at the percentage of impressions I get from various sources on Instagram."""

home = data["From Home"].sum()
hashtags = data["From Hashtags"].sum()
explore = data["From Explore"].sum()
other = data["From Other"].sum()

labels = ['From Home', 'From Hashtags', 'From Explore', 'Other']
values = [home, hashtags, explore, other]
palette_color = sns.color_palette('pastel')

plt.pie(values, labels=labels, colors=palette_color, autopct='%.0f%%')
plt.show()

"""Now, let's analyze the content of my Instagram posts. The dataset has two columns, namely caption and hashtags, which will help us understand the kind of content I post on Instagram.

Let's create wordclous of the caption column to look at the most used words in the caption of my Instagram posts.
"""

text = " ".join(i for i in data.Caption)
stopwords = set(STOPWORDS)
wordcloud = WordCloud(stopwords=stopwords, background_color="white").generate(text)
plt.style.use('classic')
plt.figure(figsize=(12, 10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

"""Now, let's create a wordcloud of the hashtags column to look at the most used hashtags in my Instagram posts."""

text = " ".join(i for i in data.Hashtags)
stopwords = set(STOPWORDS)
wordcloud = WordCloud(stopwords=stopwords, background_color="white").generate(text)
plt.figure(figsize=(12, 10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

"""Analyzing Relatioinships
Now, let's analyze relationships to find the most important factors of our Instagram reach. It will also help us in understanding how the Instagram algorithm works.
"""

sns.lmplot(data=data, x="Impressions", y="Likes", fit_reg=True, scatter_kws={"s": 20}, line_kws={"lw":1})
ax = plt.gca()
ax.set_title("Relationship Between Likes and Impressions", pad=20)
plt.xlim(0, 15000)
plt.ylim(0, 500)
plt.show()

"""There is a linear relationship between the number of likes and the reach I got on Instagram. Now, let's see the relationship between the number of comments and the number of impressions on my Instagram posts."""

sns.lmplot(data=data, x="Impressions", y="Comments", fit_reg=True, scatter_kws={"s": 30}, line_kws={"lw":1})
ax = plt.gca()
ax.set_title("Relationship Between Comments and Total Impressions", pad=20)
plt.xlim(0, 15000)
plt.ylim(0, 25)
plt.show()

"""It looks like the number of comments we get on a post doesn't affect it's reach. Now, let's have a look at the relationship between the number of shares and the number of impressions."""

sns.lmplot(data=data, x="Impressions", y="Shares", fit_reg=True, scatter_kws={"s": 30}, line_kws={"lw":1})
ax = plt.gca()
ax.set_title("Relationship Between Shares and Impressions", pad=20)
plt.ylim(0, 80)
plt.xlim(0, 40000)
plt.show()

sns.lmplot(data=data, x="Impressions", y="Saves", fit_reg=True, scatter_kws={"s": 30}, line_kws={"lw":1})
ax = plt.gca()
ax.set_title("Relationship Between Post Saves and Total Impressions", pad=20)
plt.xlim(0, 15000)
plt.ylim(0, 700)
plt.show()

"""There is a linear relationship between the number of times my post is saved and the reach of my Instagram post. Now let’s have a look at the correlation of all the columns with the Impressions column."""

correlation = data.corr()
print(correlation["Impressions"].sort_values(ascending=False))

"""In Instagram, conversation rate means how many followers you are getting from the number of profile visits from a post. The formula that you can use to calculate conversion rate is (Follow/Profile Visits) * 100. Now, let's have a look at the conversation rate of my Instagram account."""

conversion_rate = (data["Follows"].sum() / data["Profile Visits"].sum()) * 100
print(conversion_rate)

"""So the conversation rate of my Instagram account is 41% which sounds like a very good conversation rate. Let’s have a look at the relationship between the total profile visits and the number of followers gained from all profile visits."""

sns.lmplot(data=data, x="Profile Visits", y="Follows", fit_reg=True, scatter_kws={"s": 30}, line_kws={"lw":1})
ax = plt.gca()
ax.set_title("Relationship Between Profile Visits and Followers Gained", pad=20)

"""Now in this section, I will train a machine learning model to predict the reach of an Instagram post. Let’s split the data into training and test sets before training the model."""

X = np.array(data[['Likes', 'Saves', 'Comments', 'Shares', 'Profile Visits', 'Follows']])
y = np.array(data["Impressions"])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""Now here’s is how we can train a machine learning model to predict the reach of an Instagram post using Python."""

model = PassiveAggressiveRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

"""Now let’s predict the reach of an Instagram post by giving inputs to the machine learning model"""

import numpy as np
from sklearn.linear_model import LinearRegression

# Example: Creating and training a linear regression model
model = LinearRegression()
X_train = np.array([[1.0], [2.0], [3.0]])  # Replace with your actual training data
y_train = np.array([2.0, 3.0, 4.0])          # Replace with your actual target values

model.fit(X_train, y_train)

# Now you can make predictions
features = np.array([[282.0]])  # Adjust the number of features to match your model
predictions = model.predict(features)

print(predictions)